parameters:
# nothing to declare

services:
  _defaults:
    autowire: true

  LeoVie\PhpMethodsParser\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpMethodsParserBundle.php'

  LeoVie\PhpMethodsParser\Service\MethodsParser:
    public: true
    autowire: true

  PhpParser\ParserFactory: ~
  PhpParser\NodeTraverser: ~
  PhpParser\Lexer:
    arguments:
      $options:
        usedAttributes:
          - startLine
          - endLine
          - startFilePos
          - endFilePos