parameters:
# nothing to declare

services:
  LeoVie\PhpMethodsParser\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpTokenNormalizeBundle.php'

  LeoVie\PhpMethodsParser\Service\MethodsParser:
    public: true
    autowire: true